---
services:
  openvoxserver:
    image: ghcr.io/openvoxproject/openvoxserver:latest
    hostname: puppet
    environment:
      OPENVOXSERVER_HOSTNAME: puppet
    restart: always
    ports:
      - 8140:8140
    healthcheck:
      test: ["CMD-SHELL", "curl -ksS https://puppet:8140/status/v1/simple | grep -q '^running$'"]
      interval: 10s
      timeout: 5s
      retries: 5

  openvoxdb:
    image: ghcr.io/openvoxproject/openvoxdb:latest
    hostname: openvoxdb
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -ksS https://openvoxdb:8081/status/v1/simple | grep -q '^running$'"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      openvoxserver:
        condition: service_healthy
        restart: true

  postgres:
    image: docker.io/postgres:18-alpine
    hostname: postgres
    environment:
      POSTGRES_DB: openvoxdb
      POSTGRES_USER: openvoxdb
      POSTGRES_PASSWORD: openvoxdb
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U openvoxdb -d openvoxdb'"]
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - ./postgresql_init:/docker-entrypoint-initdb.d
    restart: always

networks:
  default:
    name: crafty-ov-minimal
