---
services:
  openvoxdb:
    image: ghcr.io/openvoxproject/openvoxdb:latest
    hostname: openvoxdb
    environment:
      USE_OPENVOXSERVER: false
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    healthcheck:
      test: ["CMD-SHELL", "curl -ksS https://openvoxdb:8081/status/v1/simple | grep -q '^running$'"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 8081:8081

  postgres:
    image: docker.io/postgres:18-alpine
    hostname: postgres
    environment:
      - POSTGRES_DB=openvoxdb
      - POSTGRES_USER=openvoxdb
      - POSTGRES_PASSWORD=openvoxdb
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U openvoxdb -d openvoxdb'"]
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - ./postgresql_init:/docker-entrypoint-initdb.d
    restart: always
