---
name: Release 🚀

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Release
    uses: voxpupuli/crafty/.github/workflows/release.yml@main
    with:
      allowed_owner: ${{ github.repository_owner }}
