---
name: 🚦🚥 General CI

on:
  workflow_call:
    inputs:
      shellcheck_scan_dir:
        description: "Dir to scan for shell scripts."
        required: true
        default: './bin/'
        type: "string"

jobs:
  shellcheck:
    name: 'Shell Check'
    runs-on: ubuntu-latest
    permissions:
      # required for all workflows
      security-events: write

      # only required for workflows in private repositories
      actions: read
    steps:
    - name: Repository checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        # Differential ShellCheck requires full git history
        fetch-depth: 0

    - id: ShellCheck
      name: Differential ShellCheck
      uses: redhat-plumbers-in-action/differential-shellcheck@f51c7c0d32777d00de777131d25918617a246415 # v5.5.7
      with:
        scan-directory: ${{ inputs.shellcheck_scan_dir }}

    - if: always()
      name: Upload artifact with ShellCheck defects in SARIF format
      uses: actions/upload-artifact@cf430e030ddbb5b0abf93d22962f4752f3646cd9 # v7.0.2
      with:
        name: Differential ShellCheck SARIF
        path: ${{ steps.ShellCheck.outputs.sarif }}
