---
name: Labeler 🏷️

on:
  workflow_call:
    inputs:
      allowed_owner:
        description: 'Only allow this owner'
        required: true
        type: string

jobs:
  labeler:
    permissions:
      pull-requests: write
      contents: read
    name: Labeler
    runs-on: ubuntu-latest
    if: github.repository_owner == inputs.allowed_owner
    steps:
      - uses: actions/labeler@v6
