---
name: Release 🚀

on:
  workflow_call:
    inputs:
      allowed_owner:
        description: 'Only allow this owner'
        required: true
        type: string

permissions:
  contents: read

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.repository_owner == inputs.allowed_owner
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Create Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release create ${{ github.ref_name }} --generate-notes
